<?php
declare(strict_types=1);

$equipmentImages = [
    'Smith Machine'             => '/images/equipment/smith-machine.png',
    'Bench Press'               => '/images/equipment/bench-press.png',
    'Chest Press'               => '/images/equipment/chest-press.png',
    'Shoulder Press'            => '/images/equipment/shoulder-press.png',
    'Tricep Pushdown'           => '/images/equipment/tricep-pushdown.png',
    'Lat Pulldown'              => '/images/equipment/lat-pulldown.png',
    'Rowing Machine'            => '/images/equipment/rowing-machine.png',
    'Cable Row'                 => '/images/equipment/cable-row.png',
    'Seated Row'                => '/images/equipment/seated-row.png',
    'Bicep Curl Machine'        => '/images/equipment/bicep-curl.png',
    'Preacher Curl'             => '/images/equipment/preacher-curl.png',
    'Cable Crossover'           => '/images/equipment/cable-crossover.png',
    'Leg Extension'             => '/images/equipment/leg-extension.png',
    'Leg Press'                 => '/images/equipment/leg-press.png',
    'Leg Curl'                  => '/images/equipment/leg-curl.png',
    'Lateral Raise Machine'     => '/images/equipment/lateral-raises.png',
    'Cable Lateral Raise'       => '/images/equipment/lateral-raises.png',
    'Dip Machine'               => '/images/equipment/dip-machine.png',
    'Pec Deck'                  => '/images/equipment/peck-deck.png',
    'Overhead Tricep Extension' => '/images/equipment/overhead.png',
];

$equipmentMuscles = [
    'Smith Machine'             => 'Chest, shoulders and triceps. Also effective for squats targeting quads, glutes and hamstrings.',
    'Bench Press'               => 'Primary: pectorals. Secondary: anterior deltoids and triceps.',
    'Chest Press'               => 'Primary: pectorals. Secondary: triceps and anterior deltoids.',
    'Cable Crossover'           => 'Primary: pectorals (inner and outer). Secondary: anterior deltoids.',
    'Pec Deck'                  => 'Primary: pectorals. Secondary: anterior deltoids.',
    'Lat Pulldown'              => 'Primary: latissimus dorsi. Secondary: biceps and rear deltoids.',
    'Rowing Machine'            => 'Primary: latissimus dorsi and rhomboids. Secondary: biceps, rear deltoids and core.',
    'Cable Row'                 => 'Primary: latissimus dorsi and rhomboids. Secondary: biceps, rear deltoids and core.',
    'Seated Row'                => 'Primary: latissimus dorsi and rhomboids. Secondary: biceps, rear deltoids and core.',
    'Bicep Curl Machine'        => 'Primary: biceps brachii. Secondary: brachialis and brachioradialis.',
    'Preacher Curl'             => 'Primary: biceps brachii (long head). Secondary: brachialis and brachioradialis.',
    'Tricep Pushdown'           => 'Primary: triceps brachii. Secondary: anconeus.',
    'Dip Machine'               => 'Primary: triceps brachii. Secondary: pectorals and anterior deltoids.',
    'Overhead Tricep Extension' => 'Primary: triceps brachii (long head). Secondary: anconeus.',
    'Shoulder Press'            => 'Primary: deltoids. Secondary: triceps and upper trapezius.',
    'Lateral Raise Machine'     => 'Primary: medial deltoids. Secondary: supraspinatus.',
    'Cable Lateral Raise'       => 'Primary: medial deltoids. Secondary: supraspinatus.',
    'Leg Press'                 => 'Primary: quadriceps and glutes. Secondary: hamstrings and calves.',
    'Leg Extension'             => 'Primary: quadriceps (rectus femoris, vastus group).',
    'Leg Curl'                  => 'Primary: hamstrings. Secondary: calves and glutes.',
];

$equipmentMuscleDiagrams = [
    'Smith Machine'             => ['chest', 'deltoid', 'triceps', 'quadriceps'],
    'Bench Press'               => ['chest', 'deltoid', 'triceps'],
    'Chest Press'               => ['chest', 'triceps', 'deltoid'],
    'Cable Crossover'           => ['chest', 'deltoid'],
    'Pec Deck'                  => ['chest', 'deltoid'],
    'Lat Pulldown'              => ['upper-back', 'biceps'],
    'Rowing Machine'            => ['middle-back', 'upper-back', 'biceps'],
    'Cable Row'                 => ['middle-back', 'upper-back', 'biceps'],
    'Seated Row'                => ['middle-back', 'upper-back', 'biceps'],
    'Bicep Curl Machine'        => ['biceps'],
    'Preacher Curl'             => ['biceps'],
    'Tricep Pushdown'           => ['triceps'],
    'Dip Machine'               => ['triceps', 'chest'],
    'Overhead Tricep Extension' => ['triceps'],
    'Shoulder Press'            => ['deltoid', 'triceps', 'upper-back'],
    'Lateral Raise Machine'     => ['deltoid'],
    'Cable Lateral Raise'       => ['deltoid'],
    'Leg Press'                 => ['quadriceps', 'glutes', 'hamstrings'],
    'Leg Extension'             => ['quadriceps'],
    'Leg Curl'                  => ['hamstrings', 'glutes'],
];
